# Generated by Django 5.1.2 on 2024-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_adminmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
