# Generated by Django 5.0.4 on 2024-07-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pre_Booking',
        ),
    ]
