# Generated by Django 5.0.4 on 2024-06-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_bookingmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingModels',
        ),
    ]
