# Generated by Django 5.1.2 on 2024-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_contactusmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
